///|
pub type Value = @core.Value
pub type Datum = @core.Datum
pub type EvalError = @core.EvalError
pub type Primitive = @core.Primitive
pub type PromiseState = @core.PromiseState
pub type HashtableEquiv = @core.HashtableEquiv
pub type HashtableOp = @core.HashtableOp
pub type RecordProcKind = @core.RecordProcKind
pub type ConditionProcKind = @core.ConditionProcKind
pub type EnumSetProcKind = @core.EnumSetProcKind
pub type SyntaxRulesKind = @core.SyntaxRulesKind
pub type MacroTransformer = @core.MacroTransformer

